feat: Diploma-stage 1 v0.0.1
sarcazmatic/java-explore-with-me pull request #3
Opened 2023-05-25 20:48 UTC by sarcazmatic

Функционал сервера работает
Докер собирается

2023-05-25 20:51 UTC, sarcazmatic commented
Открыл доступ

2023-05-26 20:26 UTC, Frilock requested changes
Добрый вечер, оставил ряд мелких комментариев к работе.

2023-05-26 20:26 UTC, Frilock commented on stats/stats-client/pom.xml
> +        <dependency>
Между пропертями лучше 1 строчку пропускать, удобнее читается

2023-05-26 20:26 UTC, Frilock commented on stats/stats-client/src/main/java/ru/practicum/client/BaseController.java
> +        log.info("client ip: {}", request.getRemoteAddr());
Можно в 1 строчку оба лога объединить =)

2023-05-26 20:26 UTC, Frilock commented on stats/stats-client/src/main/java/ru/practicum/client/BaseController.java
> +        if (request.getParameter("uris") == null) {
Можно заменить на тернарное выражение, будет выглядеть компактнее

2023-05-26 20:26 UTC, Frilock commented on stats/stats-dto/src/main/java/ru/practicum/dto/EndpointHitMapper.java
> +    private static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
по code style - FORMATTER

2023-05-26 20:26 UTC, Frilock commented on stats/stats-server/src/main/java/ru/practicum/controller/StatController.java
> +        if (request.getParameter("uris") == null) {
Аналогично

2023-05-26 20:26 UTC, Frilock commented on stats/stats-server/src/main/java/ru/practicum/repository/StatRepository.java
> +    @Query("SELECT new ru.practicum.model.ViewStats(h.app, h.uri, COUNT(DISTINCT h.ip)) FROM EndpointHit h " +
А зачем вам Query? Вроде в теле запроса умещается все. Вроде обсуждали данный момент, что лучше обходиться без Query

2023-05-26 20:26 UTC, Frilock commented on stats/stats-server/src/main/java/ru/practicum/service/StatServiceImpl.java
> +        if (uris.isEmpty()) {
Разбейте метод на несколько меньших, а то выглядит не очень эстетично

2023-05-26 20:26 UTC, Frilock commented on stats/stats-server/src/main/java/ru/practicum/service/StatServiceImpl.java
> +                return list.stream().map(o -> ViewStatsMapper.toDto(o)).collect(Collectors.toList());
Строчки с ретурном повторяются, их можно из под ифа вынести

2023-05-26 20:26 UTC, Frilock commented on stats/stats-server/src/main/resources/schema.sql
> +    app     VARCHAR(255)                            NOT NULL,
На мой взгляд, вы не раздумывали над размерностью полей, вот, например, зачем для ip 255 символов? Когда указываете размерность, нужно попытаться немного спланировать и подумать об целесообразности того или иного значения

2023-05-26 20:41 UTC, sarcazmatic commented on stats/stats-client/pom.xml
> +        <dependency>
done

2023-05-26 20:42 UTC, sarcazmatic commented on stats/stats-client/src/main/java/ru/practicum/client/BaseController.java
> +        log.info("client ip: {}", request.getRemoteAddr());
done

2023-05-26 20:45 UTC, sarcazmatic commented on stats/stats-client/src/main/java/ru/practicum/client/BaseController.java
> +        if (request.getParameter("uris") == null) {
done

2023-05-26 20:47 UTC, sarcazmatic commented on stats/stats-dto/src/main/java/ru/practicum/dto/EndpointHitMapper.java
> +    private static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
done

2023-05-26 20:48 UTC, sarcazmatic commented on stats/stats-server/src/main/java/ru/practicum/controller/StatController.java
> +        if (request.getParameter("uris") == null) {
done

2023-05-26 21:13 UTC, sarcazmatic commented on stats/stats-server/src/main/java/ru/practicum/service/StatServiceImpl.java
> +                return list.stream().map(o -> ViewStatsMapper.toDto(o)).collect(Collectors.toList());
done

2023-05-26 22:42 UTC, sarcazmatic commented on stats/stats-server/src/main/java/ru/practicum/repository/StatRepository.java
> +    @Query("SELECT new ru.practicum.model.ViewStats(h.app, h.uri, COUNT(DISTINCT h.ip)) FROM EndpointHit h " +
Я возвращаю ViewStats,  а не хит, поэтому в query приходится указывать конструктор.
Побился с методом, но не разобрался, как из него убрать query, без добавления новых мапперов и каких-то сверхсложных (а потому полагаю ошибочных) конвертаций из типа в тип

2023-05-26 22:53 UTC, sarcazmatic commented on stats/stats-server/src/main/resources/schema.sql
> +    app     VARCHAR(255)                            NOT NULL,
да, честно говоря, взял из раннее сделанного)
done

2023-05-26 22:54 UTC, sarcazmatic commented on stats/stats-server/src/main/java/ru/practicum/service/StatServiceImpl.java
> +        if (uris.isEmpty()) {
разбил на этот и formViewDtoResponseList
done

2023-05-26 22:57 UTC, sarcazmatic commented on stats/stats-server/src/main/java/ru/practicum/repository/StatRepository.java
> +    @Query("SELECT new ru.practicum.model.ViewStats(h.app, h.uri, COUNT(DISTINCT h.ip)) FROM EndpointHit h " +
Я попробовал сделать интерфейс ViewStatsShort, но у него не может быть getHits() тк у EndpointHit нет такого get() и без count(h.id) не получается сваять итоговый ViewStatsDtoResponse.

2023-05-27 14:04 UTC, Frilock approved these changes
Принял

2023-05-29 14:48 UTC, merged