feat: Diploma-stage 3 v0.1 (добавлены комментарии событий)
sarcazmatic/java-explore-with-me pull request #5
Opened 2023-06-19 19:09 UTC by sarcazmatic

2023-06-20 06:47 UTC, Frilock requested changes
Доброе утро, по работе: просьба разделить работу с комментариями и ивентами в разные контроллеры/сервисы.
Кроме того, кое где слетело форматирование, а так же присутствуют лишние комментарии и пропуски строк

2023-06-20 06:47 UTC, Frilock commented on ewm/src/main/java/ru/practicum/api/admin/controller/AdminCommentsController.java
> +    @DeleteMapping("/{commentId}") //затестить
Что за странный комментарий?) Такой оставлять нельзя

2023-06-20 06:47 UTC, Frilock commented on ewm/src/main/java/ru/practicum/api/admin/controller/AdminCommentsController.java
> +public class AdminCommentsController {
А разве админ может только удалять комментарий? Вроде же еще и обновлять. Мне кажется нужен метод updateComment

2023-06-20 06:47 UTC, Frilock commented on ewm/src/main/java/ru/practicum/api/admin/service/AdminCommentsServiceImpl.java
> +    public void deleteComment(long commentId) {
Транзакция нужна

2023-06-20 06:47 UTC, Frilock commented on ewm/src/main/java/ru/practicum/api/admin/service/AdminEventsServiceImpl.java
> +            } catch (IndexOutOfBoundsException ignored) {
А почему мы такую ошибку допускаем, но игнорируем ее? Не очень понял

2023-06-20 06:47 UTC, Frilock commented on ewm/src/main/java/ru/practicum/api/admin/service/AdminEventsServiceImpl.java
> +
Лишняя пустая строка

2023-06-20 06:47 UTC, Frilock commented on ewm/src/main/java/ru/practicum/api/admin/service/AdminEventsServiceImpl.java
> +
Лишняя пустая строка

2023-06-20 06:47 UTC, Frilock commented on ewm/src/main/java/ru/practicum/api/all/controller/PublicEventsController.java
> +    public List<CommentDtoResponse> getComments(@PathVariable long eventId) {
Давайте отдельный публичный контроллер для комментариев сделаем, кроме того, кажется, что нужен еще метод получения комментария по id

2023-06-20 06:47 UTC, Frilock commented on ewm/src/main/java/ru/practicum/api/user/service/PrivateCommentsServiceImpl.java
> +package ru.practicum.api.user.service;import lombok.RequiredArgsConstructor;import lombok.extern.slf4j.Slf4j;import org.springframework.stereotype.Service;import ru.practicum.dto.comment.*;impo
С классом что то странное, как будто слетелакодировка.

2023-06-20 06:47 UTC, Frilock commented on ewm/src/main/java/ru/practicum/dto/comment/CommentMapper.java
> +    public static Comment fromNewCommentDto(NewCommentDto newCommentDto) {
Для входящих параметров поставьте NonNull аннотацию, поскольку тут null прийти не может

2023-06-20 09:33 UTC, sarcazmatic commented on ewm/src/main/java/ru/practicum/api/user/service/PrivateCommentsServiceImpl.java
> +package ru.practicum.api.user.service;import lombok.RequiredArgsConstructor;import lombok.extern.slf4j.Slf4j;import org.springframework.stereotype.Service;import ru.practicum.dto.comment.*;impo
Очень странно, в идее все чисто. Возможно, при выгрузке архива что-то слетело, постараюсь исправить

2023-06-20 18:16 UTC, sarcazmatic commented
Немного почистил последнюю версию – привел строки к единообразию, схлопнул повторяющиеся строки кода в метод, избавился от проблемы с IndexOutOfBounds – вообще не понял, как допустил ее в прошлый раз.

Возможно, это последний мой коммит. Если так, Иван, спасибо, что были со мной на всем этом пути :)

2023-06-21 06:37 UTC, Frilock approved these changes
Евгений, работу принимаю, есть еще мелкие комментарии, но не критично. 
Успехов в дальнейшей карьере.

2023-06-21 06:37 UTC, Frilock commented on ewm/src/main/java/ru/practicum/api/admin/service/AdminCommentsServiceImpl.java
> +        for (Comment c : comments) {
Лучше comment

2023-06-21 06:37 UTC, Frilock commented on ewm/src/main/java/ru/practicum/api/admin/service/AdminEventsServiceImpl.java
> +    private static final String URI_PREFIX = "/events";
static final поля идут выше чем просто final поля. Вообще вроде мелочь, потом руку набьете. Не знаю говорил или нет, можете попробовать установить в IDEA плагин sonarlint - статический анализатор кода, он показывает ряд хороших практик

2023-06-21 06:37 UTC, Frilock commented on ewm/src/main/java/ru/practicum/api/admin/service/AdminEventsServiceImpl.java
> +        List<ViewStatsDtoResponse> list = baseClient.getStats(LocalDateTime.now().minusYears(100),
просто list лучше не называть, list чего то

2023-06-21 06:37 UTC, Frilock commented on ewm/src/main/java/ru/practicum/api/all/service/PublicCommentsServiceImpl.java
> +@Slf4j
Лишняя аннотация логгирования

2023-06-23 13:04 UTC, merged